project:
  type: website
  output-dir: docs
website:
  title: "NM2207 Datastory by Sherise Tan Qin Lin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

